### ISSUE TITLE
Establish a Git-flow process

### ISSUE THREAD

**Issue by shayneptorres** [suicidesafetyplan/safetyplan-ios#10]
In order to ensure that contributors are not merging directly into master, and that there are no confusions with feature/bug/enhancement branches I would suggest that we establish a gitflow process. 

I recommend that we create a `develop` branch that all feature/bug/enhancement branches will branch off. All PRs should be made against the `develop` branch. Only specified admin can merge `develop` back into the `master`. The `master` branch is the final state before the new build is submitted to app store.

Please let me know if there are any suggestions/comments/critiques/concerns.

**Comment by eddielement** [comment]
I'd be down for this. Alternatively, we could make a Release branch that is the final submitted build for each Release and treat master like Develop. Any thoughts? Maybe we should make a contributing.MD file outlining the process?

**Comment by shayneptorres** [comment]
As the master of the repo, it is totally up to you. In my experience, its been convention to have the develop branch which gets branched off for work, PR'd and then merged back into `master`. I believe that is the [official Git Flow process](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) too but it's not a hill that I will die on. As long as we can keep the work organized.

**Comment by eddielement** [comment]
Sounds good, I'll make a Release branch and then work on a Contributing.MD file today. Will reach out for feedback once I have a draft up! :)
