### ISSUE TITLE
CrisisViewController Obj-C -> Swift Conversion

### ISSUE THREAD

**Issue by shayneptorres** [suicidesafetyplan/safetyplan-ios#11]
Converting the CrisisViewController which is currently written in Objective-C to Swift

**Comment by shayneptorres** [comment]
I just finished up the work for the `CrisisViewController` swift conversion but I am unable to push my changes and create a PR. I was told I do not have the correct permissions. How do I go about getting that?

**Comment by eddielement** [comment]
That's weird, I'm not sure what the issue is. I'm combing through the Settings and can't find any restrictions on pull requests. I'll invite you as a collaborator to get around this for now, but I'd be interested in finding a solution if anyone else has an idea.

**Comment by eddielement** [comment]
@shayneptorres I figured it out while writing the Contributing guidelines! If you follow the steps below, it should be easy. https://github.com/suicidesafetyplan/safetyplan-ios/blob/master/contributing.md

**Comment by shayneptorres** [comment]
Closed with [this branch](https://github.com/suicidesafetyplan/safetyplan-ios/pull/14)
