### ISSUE TITLE
Implement RealmDB for the data persistence layer

### ISSUE THREAD

**Issue by shayneptorres** [suicidesafetyplan/safetyplan-ios#19]
Currently the app is persisting data using `UserDefaults`. While not an incorrect usage, it would be better to use a dedicated DB framework to manage modeling, saving, and querying data. After discussion in [this issue](https://github.com/suicidesafetyplan/safetyplan-ios/issues/12) we have decided to move forward with using [RealmDB](https://realm.io/docs/swift/latest/) as our dedicated data persistence layer. 

This issue will track the implementation of RealmSwift in the iOS application

**Comment by shayneptorres** [comment]
I want to apologize for the lack of updates in the last couple weeks. With everything going on I got distracted with some personal stuff. I am still planning on finishing this work and pushing the commits. If you have any questions please reach out. Also I hope you all are staying healthy

**Comment by eddielement** [comment]
Same to you @shayneptorres !
