### ISSUE TITLE
Export Safety Plan

### ISSUE THREAD

**Issue by eddielement** [suicidesafetyplan/safetyplan-ios#22]
Got this feature request from a therapist: 

"Hello, I wanted to say that I really like your suicide safety plan app. I wanted to ask for a recommendation. I’m a therapist and use it with my clients but I usually also want a copy of the plan when they create it. Is it possible to add a feature that would allow users to send their plan to people?"

**Comment by pankova** [comment]
Hi! I very like your project. I could help with this issue. I can make a share button at the top of the Plan screen. Clicking on the button will share a text version of all filled items. What do you think?

<img width="250" alt="Screenshot 2022-07-29 at 12 24 22" src="https://user-images.githubusercontent.com/7028613/181830300-f7fe7aac-98f3-4913-824b-f704959b01ef.png">

**Comment by eddielement** [comment]
@pankova That sounds great!

**Comment by pankova** [comment]
Tomorrow I'll check the export for the Contacts to make sure the numbers are also exported as names.
