### ISSUE TITLE
Fix Issues when building with XCode 13

### ISSUE THREAD

**Issue by eddielement** [suicidesafetyplan/safetyplan-ios#24]
When building the app in XCode 13, there are several UI issues. 

- Transparent splash screen

- Transparent navigation bar till I scroll up the screen

The video with 1 and 2: https://user-images.githubusercontent.com/7028613/182032101-e62f3157-217c-4e1d-a312-3a583481197f.mov

- Untappable tip textfield and +Add another button.

**Comment by pankova** [comment]
I could help with the issue or with another task, if plan to do it.

**Comment by eddielement** [comment]
Your help would be greatly appreciated! I did some research that might be helpful: 

- To get the simulator working on M1 Macs, go to Build Settings -> All -> Excluded Architectures -> add 'arm64' to iOS Simulator
- The navigation bar thing seems to be due to an outdated bar. In the storyboard, I can highlight the navigation bar and select a type and that makes it opaque again, but then it just needs to be colored blue.

**Comment by pankova** [comment]
As part of this task, minimum iOS version can be bumped to iOS 13, if you don't mind.

**Comment by pankova** [comment]
Also I've noticed, there is a problem with the tab bar shadow until scrolling down. I'll try to fix it in the PR as a part of Xcode 13 issues.
<img width="200" alt="Screenshot 2022-08-01 at 21 36 45" src="https://user-images.githubusercontent.com/7028613/182292725-fdf61afb-ce98-454f-a04d-816ae0bee3cb.png">

**Comment by eddielement** [comment]
> As part of this task, minimum iOS version can be bumped to iOS 13, if you don't mind.

Sounds good! :)
