### ISSUE TITLE
The National Suicide Prevention Lifeline is now the 988 Suicide & Crisis Lifeline

### ISSUE THREAD

**Issue by thomasjzimmer** [suicidesafetyplan/safetyplan-ios#28]
First, great app. I am a [child and adolescent psychiatrist](https://medicine.umich.edu/dept/psychiatry/thomas-zimmer-md) and I really value that my young patients can always have this plan on them because they always have their phone. A paper plan is great, but is probably sitting in a drawer at home when they need it. There are some very recent updates to the National Suicide Prevention Lifeline that are relevant for the app.

Over this summer, the National Suicide Prevention Lifeline formally switched to be the "988 Suicide & Crisis Lifeline". See [988lifeline.org](988lifeline.org). The FCC has now made the three digit dialing number 988 active in all US states and territories, just like 911. Unlike 1-800-273-TALK (8255) number, which is still active, the 988 number works with both voice and SMS, and [988lifeline.org](988lifeline.org) also has a web-based chat. Especially for privacy reasons, some youth prefer the web-based chat because their parents won't see it on the phone bill. 988lifeline.org is also the best single best starting point for the available diversity of crisis support resources that I have encountered, including resources for veterans, LGBTQ+, Spanish speaking, black, native American, hard-on-hearing, sign language lifeline, maternal depression, individuals with autism, and more.  

Could we update the crisis resources to the new 988 and [988lifeline.org](988lifeline.org) resources? Please don't hesitate to reach out.

**Comment by igroti** [comment]
@eddielement I believe this was done..?
