### ISSUE TITLE
Chore: fix Xcode warnings and apply recommended settings

### ISSUE THREAD

**Issue by igroti** [suicidesafetyplan/safetyplan-ios#30]
From: https://github.com/suicidesafetyplan/safetyplan-ios/issues/13#issuecomment-1748544448

I'm gonna G-d willing work on this now, and after go back to https://github.com/suicidesafetyplan/safetyplan-ios/issues/13

![screenshot of xcode warnings](https://user-images.githubusercontent.com/19246409/272866024-be5ed4f1-cd24-4dc1-8f8a-ab25376e743d.png)

**Comment by igroti** [comment]
@eddielement we still want this, right?

**Comment by igroti** [comment]
I think this was mostly done... perhaps I'm mixing up with a different issue or branch. I guess I will try to keep in mind to make future issues more specifically detailed, so it's easier to tell if they were done or otherwise.

**Comment by eddielement** [comment]
Sounds good to me! @DaniSpringer :)
