### ISSUE TITLE
Errors when trying to build clone from master

### ISSUE THREAD

**Issue by igroti** [suicidesafetyplan/safetyplan-ios#32]
As of now, it seems various errors occur when copying the project and attempting to run it from Xcode, making it tricky to practically contribute to it. Fixing those would be great, and attaching instructions for getting the project up and running locally (such as setting up pods) would be great too!

Thanks

P.S.: after cleaning and rebuilding, and applying Xcode recommended settings and rebuilding, the errors seem to change, but they all look something like this: (meaning they all have long logs, as opposed to something concise like "could not cast X to Y")

<img width="870" alt="Screenshot 2023-10-06 at 7 48 55 AM" src="https://github.com/suicidesafetyplan/safetyplan-ios/assets/19246409/ae0a2a24-b70a-475d-a99e-a726057e810c">

**Comment by eddielement** [comment]
@DaniSpringer I just refactored it from Cocoapods to Swift Package Manager. Could you check out the branch refactor/switch-to-spm and let me know if it works smoothly? :)

**Comment by igroti** [comment]
@eddielement been a while, sorry for delay :)

Gonna try it now. It seems to have created untracked pod files.
Just wondering: what are pods needed for in this project, as of now? (and especially as of the refactor/switch-to-spm branch)

Thanks!

**Comment by igroti** [comment]
@eddielement that branch did make it much easier to get up and running, so thank you!
