### ISSUE TITLE
Native iOS Dark Mode Support

### ISSUE THREAD

**Issue by eddielement** [suicidesafetyplan/safetyplan-ios#4]
Right now the app forces light mode even if the user is in dark mode.

**Comment by NinjaSnail42** [comment]
This should be pretty easy and straight forward. I can work on this. Does anyone have certain colors in mind? I will probably try to use similar dark grays and blacks that in the system apps.

**Comment by eddielement** [comment]
Sounds great! I'd use the System Background Color for the background and the Label Color for all text in the Storyboards. Otherwise, taking the colors from the system apps sounds like a good approach.

**Comment by NinjaSnail42** [comment]
I'm having troubles getting this to work. Dark mode should already be somewhat working when you run an app on iOS 13 from Xcode, but I get nothing. I have tried changing the iOS target to iOS 13, I have tried setting UI Interface Mode to Dark in the Info.plist file, and still nothing... I've done this on my own application with no issue, so I'm not sure if there is some conflicting configuration that I am missing or what.

**Comment by eddielement** [comment]
Strange - it works for me if I just delete the User Interface Style from the Info.plist and then open a simulator, go to settings and set it for dark mode.

**Comment by NinjaSnail42** [comment]
Thanks! I didn't realize that User Interface Style was already defined.... I was trying to define it again to force Dark Mode. Whoops.

**Comment by NinjaSnail42** [comment]
I'm looking to get some feedback on Dark Mode. I was going with the primary system background color (black/white) but I'm thinking that secondary system background color looks better (very dark gray/very light gray). Thoughts?

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-09 at 00 43 11](https://user-images.githubusercontent.com/10276641/76186168-6f1bab00-619f-11ea-9a3a-b226c3cd9f0f.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-09 at 00 43 15](https://user-images.githubusercontent.com/10276641/76186171-73e05f00-619f-11ea-9a00-f104ce563061.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-09 at 00 43 13](https://user-images.githubusercontent.com/10276641/76186173-7642b900-619f-11ea-94d8-a5b6791708ae.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-09 at 00 43 08](https://user-images.githubusercontent.com/10276641/76186177-793da980-619f-11ea-94e4-1fc9091c95f3.png)

**Comment by eddielement** [comment]
They look roughly equivalent to me. Maybe we can do a hybrid like Apple does on their settings app? Where the parts with text on it are a lighter gray whereas the parts that are empty are dark. 

![image](https://user-images.githubusercontent.com/7614803/76246601-65805a80-6214-11ea-870c-eca86db3dd02.png)

**Comment by NinjaSnail42** [comment]
This issue can be closed now since the changes have been merged. I don't have the ability to close it though.

**Comment by eddielement** [comment]
Thanks! :)
